import torch
import numpy as np

#x = torch.tensor(3.0)
#y = torch.tensor(2.0)
#z = torch.arange(4)
#print(x + y, ";",x * y, ";", x / y, ";", x**y, ";", z, ";", len(z), ";", z.shape,"\n")
A = torch.arange(20,dtype=torch.float32).reshape(5, 4)
#A = torch.arange(16).reshape(4,4)
B = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
C=(B == B.T)
#print(A,"\n",A.T,"\n",B,"\n",C,"\n")
#X = torch.arange(24).reshape(2, 3, 4)
X = torch.arange(24, dtype=torch.float32).reshape(2, 3, 4)
#X = torch.arange(27, dtype=torch.float32).reshape(3, 3, 3)
Y = X.clone()  # 通过分配新内存，将A的一个副本分配给B
Z = X + Y
a=2
#print(X,"\n",Z,"\n",X*Y,"\n",a + X,"\n",(a * X).shape,"\n")
#x = torch.arange(4, dtype=torch.float32)
#A_sum_axis0 = A.sum(axis=0)
#A_sum_axis1 = A.sum(axis=1)
#A_sum_axis2 = A.sum(axis=[0,1])
#print(x,"\n",x.sum(),"\n",A.shape,"\n", A.sum(),"\n")
#print(A_sum_axis0,"\n",A_sum_axis0.shape,"\n",A_sum_axis1,"\n",A_sum_axis1.shape,"\n",A_sum_axis2,"\n",A_sum_axis2.shape)
#print(A_sum_axis0,"\n",A_sum_axis0.shape,"\n",A_sum_axis1,"\n",A_sum_axis1.shape,"\n",A/A_sum_axis0,"\n",A/A_sum_axis1)
X_sum_axis0 = X.sum(axis=0)
X_sum_axis1 = X.sum(axis=1)
X_sum_axis2 = X.sum(axis=2)
#print(X_sum_axis0,"\n",X_sum_axis0.shape,"\n",X_sum_axis1,"\n",X_sum_axis1.shape,"\n")
#X_sum_axis00 = X.sum(axis=0,keepdims=True)
#X_sum_axis01 = X.sum(axis=1,keepdims=True)
#print(X,"\n",X_sum_axis0,"\n",X/X_sum_axis0,"\n",X_sum_axis1,"\n",X/X_sum_axis1,"\n")
print(X_sum_axis0,"\n",X_sum_axis0.shape,"\n",X_sum_axis1,"\n",X_sum_axis1.shape,"\n",X_sum_axis2,"\n",X_sum_axis2.shape,"\n")
#print(X_sum_axis1,"\n",X_sum_axis1.shape,"\n",X_sum_axis01,"\n",X_sum_axis01.shape,"\n")
#print(X/X_sum_axis1,"\n",X/X_sum_axis01)
x = torch.arange(4, dtype=torch.float32)
y = torch.ones(4, dtype = torch.float32)
#print(x,"\n",y,"\n",torch.dot(x,y),"\n")
#print(A.shape,"\n",x.shape,"\n",torch.mv(A,x),"\n")
B = torch.ones(4, 3)
#print(torch.mm(A,B))
u=torch.tensor([3.0,-4.0])
#print(torch.norm(u),"\n",torch.abs(u),"\n",torch.abs(u).sum(),"\n",torch.ones((4,9)))
#print(len(X))

